modules:
  controller:
    cooling_down_duration: 60
    max_target_pod: 20
    services:
      s0: 100
      s1: 100
      s2: 100
      s3: 100
      s4: 100
      s5: 100
      s6: 100
    is_test: true
    test_data_path: "data/traffic.csv"

  latency_predictor_model:
    model_path: "models/latency_predictor_model/v1"
    num_target: 7

  metrics_fetcher:
    prometheus_url: "http://prometheus-nodeport.monitoring.svc.cluster.local:9090"

  resource_manager:

  traffic_forecaster_model:
    model_path: "models/traffic_forecaster_model/v1"

exporter:
  port: 8080
