apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: k8s-scaler-monitor
spec:
  selector:
    matchLabels:
      prometheus.io/scrape: "true"
  podMetricsEndpoints:
    - port: "http-k8sscalerport"
      path: "/metrics"
