apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: k8s-scaler-monitor
  namespace: k8s-scaler
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      prometheus.io/scrape: "true"
  podMetricsEndpoints:
    - port: "http-scalerport"
      path: "/metrics"
